name: ${PROJECT_NAME}

x-services:
  backend-base: &backend-base
    image: ${PROJECT_NAME}-backend-base:latest
    build:
      context: .
    volumes:
      - ./app:/app
    depends_on:
      - postgres
      - redis
      - rabbitmq
    env_file:
      - .env


services:

  backend:
    <<: *backend-base
    command: backend-local
    ports:
      - "${EXTERNAL_PORT_BACKEND}:8000"

  postgres:
    image: postgres:14
    shm_size: 1g
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${EXTERNAL_PORT_POSTGRES}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth-host=md5

  redis:
    image: "redis:6"
    volumes:
      - "redis_data:/data"

  worker-scraper-raw-data:
    <<: *backend-base
    command: worker-scraper-raw-data

  worker-beat:
    <<: *backend-base
    command: worker-beat

  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.12.0-debian-11-r0
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
    environment:
      - RABBITMQ_USER=${RABBIT_USER:-user}
      - RABBITMQ_PASSWORD=${RABBIT_PASSWORD:-password}
    ports:
      - "${EXTERNAL_PORT_RABBITMQ:-5672}:5672"
      - "${EXTERNAL_PORT_RABBITMQ_MANAGEMENT:-15672}:15672"

volumes:
  pg-data:
  redis_data:
  rabbitmq_data:
