# Generated by Django 5.2 on 2025-05-31 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scholar Author',
                'verbose_name_plural': 'Scholar Authors',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ScholarRawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(unique=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='scholar_raw_records', to='dip.scholarauthor')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholar_raw_records', to='dip.profile')),
            ],
            options={
                'verbose_name': 'Scholar Raw Record',
                'verbose_name_plural': 'Scholar Raw Records',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
