# Generated by Django 5.2 on 2025-05-31 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dip', '0002_scholarauthor_scholarrawrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarrawrecord',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholar_raw_records', to='dip.profile'),
        ),
    ]
