# Generated by Django 5.2 on 2025-05-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dip', '0003_alter_scholarrawrecord_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarrawrecord',
            name='authors',
        ),
    ]
