# Generated by Django 5.2 on 2025-06-07 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dip', '0005_scholarrawrecord_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarauthor',
            name='affiliations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scholarauthor',
            name='citation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholarauthor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarauthor',
            name='h_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarauthor',
            name='paper_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholarauthor',
            name='semantic_scholar_id',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarauthor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='citation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='influential_citation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='is_open_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='reference_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='semantic_scholar_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='venue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scholarrawrecord',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholarrawrecord',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='scholarauthor',
            index=models.Index(fields=['h_index'], name='dip_scholar_h_index_6770de_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarauthor',
            index=models.Index(fields=['citation_count'], name='dip_scholar_citatio_b50cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarrawrecord',
            index=models.Index(fields=['publication_year'], name='dip_scholar_publica_f339c4_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarrawrecord',
            index=models.Index(fields=['citation_count'], name='dip_scholar_citatio_1a6bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarrawrecord',
            index=models.Index(fields=['venue'], name='dip_scholar_venue_71ecb1_idx'),
        ),
    ]
