# Generated by Django 5.2 on 2025-06-07 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dip', '0006_scholarauthor_affiliations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('limit', models.IntegerField(default=100)),
                ('fields_of_study', models.JSONField(default=list)),
                ('publication_types', models.JSONField(default=list)),
                ('min_citation_count', models.IntegerField(blank=True, null=True)),
                ('open_access_only', models.BooleanField(default=False)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('papers_found', models.IntegerField(default=0)),
                ('papers_saved', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_sessions', to='dip.profile')),
            ],
            options={
                'verbose_name': 'Scraping Session',
                'verbose_name_plural': 'Scraping Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scholarrawrecord',
            name='scraping_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='dip.scrapingsession'),
        ),
        migrations.AddIndex(
            model_name='scrapingsession',
            index=models.Index(fields=['profile', 'status'], name='dip_scrapin_profile_f3bf95_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapingsession',
            index=models.Index(fields=['task_id'], name='dip_scrapin_task_id_7b99d8_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapingsession',
            index=models.Index(fields=['created_at'], name='dip_scrapin_created_7f2d34_idx'),
        ),
    ]
